update terraform code to version 0.12
skyscrapers/terraform-network pull request #23
Opened 2019-06-06 13:03 UTC by venturel

2019-06-06 14:13 UTC, Komorebi-E approved these changes
As SM, LGTM. E.g. follows the guidelines for Splat, e.g. `aws_eip.nat_gateway[count.index].id`

2019-06-06 14:32 UTC, iuriaranda requested changes
Some details

2019-06-06 14:32 UTC, iuriaranda commented on nat_gateway/main.tf
> +terraform {
Can you use a `versions.tf`  file? 😛

2019-06-06 14:32 UTC, iuriaranda commented on nat_gateway/output.tf
> +  value = [aws_nat_gateway.gateway.*.id]
you don't need the list notation here, as `aws_nat_gateway.gateway.*.id` is already a list

2019-06-06 14:32 UTC, iuriaranda commented on subnets/outputs.tf
> +  value = [aws_subnet.subnets.*.id]
Same here about the list notation

2019-06-06 14:32 UTC, iuriaranda commented on vpc/main.tf
> +    merge(var.extra_tags_vpc, var.tags),
you can simplify this in a single merge function

```
tags = merge(
  var.extra_tags_vpc,
  var.tags,
  {
    "Name"        = "${var.project} ${var.environment} VPC"
    "Environment" = var.environment
    "Project"     = var.project
  },
)
```

2019-06-06 14:32 UTC, iuriaranda commented on vpc/outputs.tf
> +  value       = [aws_route_table.private.*.id]
Same here and the next output about the list notation

2019-06-07 07:08 UTC, iuriaranda approved these changes

2019-06-07 07:27 UTC, iuriaranda requested changes
The readme should be updated as well with the variable type changes and the examples

2019-06-07 10:21 UTC, iuriaranda commented on subnets/variables.tf
>    default = "0"
The type of this variable should be enforced to a `number` as well

2019-06-07 10:21 UTC, iuriaranda commented on nat_gateway/variables.tf
> +  type = list(string)
The type changes should also be reflected in the readme documentation

2019-06-13 11:05 UTC, iuriaranda approved these changes

2019-06-13 11:23 UTC, merged